"""empty message

Revision ID: 0f3a51c0615e
Revises: e0679bf586bf
Create Date: 2023-02-15 12:15:19.962039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f3a51c0615e'
down_revision = 'e0679bf586bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_tags')
    op.drop_table('tags')
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('src', sa.Text(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('da')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('developer_id', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('publisher_id', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('publish_date', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_product_publish_date'), ['publish_date'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['publisher_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['developer_id'], ['id'])
        batch_op.drop_column('publisher')
        batch_op.drop_column('cost')
        batch_op.drop_column('developer')
        batch_op.drop_column('publishDate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publishDate', sa.VARCHAR(length=32), nullable=False))
        batch_op.add_column(sa.Column('developer', sa.VARCHAR(length=32), nullable=False))
        batch_op.add_column(sa.Column('cost', sa.VARCHAR(length=32), nullable=False))
        batch_op.add_column(sa.Column('publisher', sa.VARCHAR(length=32), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_product_publish_date'))
        batch_op.drop_column('publish_date')
        batch_op.drop_column('publisher_id')
        batch_op.drop_column('developer_id')
        batch_op.drop_column('price')

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('da', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'tag', ['da'], ['id'])
        batch_op.drop_column('src')

    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_tags',
    sa.Column('tag_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('tag_id', 'product_id'),
    sa.UniqueConstraint('product_id'),
    sa.UniqueConstraint('tag_id')
    )
    # ### end Alembic commands ###
