"""empty message

Revision ID: e0679bf586bf
Revises: 
Create Date: 2023-01-05 14:27:15.861490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0679bf586bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    op.drop_table('product_categories')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('logo', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('cost', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('developer', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('publisher', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('publishDate', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('synopsis', sa.Text(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.create_unique_constraint(None, ['title'])
        batch_op.drop_column('username')
        batch_op.drop_column('email')
        batch_op.drop_column('password')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Text(), nullable=False))
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('role')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=55), nullable=False))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=16), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('synopsis')
        batch_op.drop_column('publishDate')
        batch_op.drop_column('publisher')
        batch_op.drop_column('developer')
        batch_op.drop_column('cost')
        batch_op.drop_column('logo')
        batch_op.drop_column('title')

    op.create_table('product_categories',
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('category_id', 'product_id'),
    sa.UniqueConstraint('category_id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
