"""empty message

Revision ID: f68c5708ec63
Revises: 4509edcab5df
Create Date: 2023-02-15 12:29:29.980427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f68c5708ec63'
down_revision = '4509edcab5df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('src', sa.Text(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('da')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('developer_id', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('publisher_id', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('publish_date', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_product_publish_date'), ['publish_date'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_product_id'), ['id'])
        batch_op.create_unique_constraint(batch_op.f('uq_product_title'), ['title'])
        batch_op.create_foreign_key(batch_op.f('fk_product_developer_id_user'), 'user', ['developer_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_product_publisher_id_user'), 'user', ['publisher_id'], ['id'])
        batch_op.drop_column('cost')
        batch_op.drop_column('developer')
        batch_op.drop_column('publishDate')
        batch_op.drop_column('publisher')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_tag_id'), ['id'])
        batch_op.create_unique_constraint(batch_op.f('uq_tag_name'), ['name'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_id'), ['id'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_id'), type_='unique')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_tag_name'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_tag_id'), type_='unique')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publisher', sa.VARCHAR(length=32), nullable=False))
        batch_op.add_column(sa.Column('publishDate', sa.VARCHAR(length=32), nullable=False))
        batch_op.add_column(sa.Column('developer', sa.VARCHAR(length=32), nullable=False))
        batch_op.add_column(sa.Column('cost', sa.VARCHAR(length=32), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_product_publisher_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_product_developer_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_product_title'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_product_id'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_product_publish_date'))
        batch_op.drop_column('publish_date')
        batch_op.drop_column('publisher_id')
        batch_op.drop_column('developer_id')
        batch_op.drop_column('price')

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('da', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'tag', ['da'], ['id'])
        batch_op.drop_column('src')

    # ### end Alembic commands ###
