"""empty message

Revision ID: fd3a0649e84b
Revises: f68c5708ec63
Create Date: 2023-02-17 12:08:10.903507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd3a0649e84b'
down_revision = 'f68c5708ec63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('logo',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('logo',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
